version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/imx-org
    username: imx-org
    password: ${{secrets.PKG_TOKEN}}
updates:
  - package-ecosystem: maven
    directory: "/"
    registries:
      - maven-github
    schedule:
      interval: daily
